services:
  mysql:
    image: mysql:8
    container_name: flover-mysql
    environment:
      MYSQL_DATABASE: flover_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    container_name: flover-be
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data:
